// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uirbicdwikvgnuounlia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpcmJpY2R3aWt2Z251b3VubGlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzMTk2NDAsImV4cCI6MjA4MTg5NTY0MH0.BfT2D31nTM7C2Zb5oQpG5kk5HlKracxauV9WGzRLIEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});